name: Run Semantic Release

on: 
  push:
    branches:
      - 'main'

concurrency: branch-verification

permissions:
  pull-requests: read
  id-token: write
  contents: write

jobs:
  semantic-release:
    runs-on:
      group: arm 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
          cache: npm
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Setup Github
        run: |
           git config user.name "$(git log -n 1 --pretty=format:%an)"
           git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env: 
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      #- name: Run Semantic Release to update Changlog and package.json version
        #run: make semantic

