name: Verify Branch
on: 
  push:
    branches:
      - '*'

concurrency: ${{ github.repository }}-verify

jobs:
  verify:
    name: Verify Branch
    uses: ./.github/workflows/resusable-verify.yml
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}} 
      
          